<?php
use CRM_Reimbursement_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_reimbursement_expense_line',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'reimbursement_expense_line',
        'table_name' => 'civicrm_value_reimbursement_expense_line',
        'title' => E::ts('Expense Line'),
        'extends' => 'Activity',
        'extends_entity_column_value:name' => [
          'expense_line_added',
          'expense_line_updated',
        ],
        'collapse_adv_display' => TRUE,
        'is_public' => FALSE,
        'is_reserved' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_reimbursement_expense_line_CustomField_expense_line_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'reimbursement_expense_line',
        'name' => 'expense_line_id',
        'label' => E::ts('Expense Line ID'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'expense_line_id',
        'fk_entity' => 'ExpenseLine',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_reimbursement_expense_line_CustomField_expense_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'reimbursement_expense_line',
        'name' => 'expense_id',
        'label' => E::ts('Expense ID'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'expense_id',
        'fk_entity' => 'Expense',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_reimbursement_expense_line_CustomField_amount',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'reimbursement_expense_line',
        'name' => 'amount',
        'label' => E::ts('Amount'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'amount',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_reimbursement_expense_line_CustomField_description',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'reimbursement_expense_line',
        'name' => 'description',
        'label' => E::ts('Description'),
        'html_type' => 'Text',
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'description',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_reimbursement_expense_line_CustomField_expense_type_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'reimbursement_expense_line',
        'name' => 'expense_type_id',
        'label' => E::ts('Expense Type'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'expense_type_id',
        'option_group_id.name' => 'expense_type',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
