<?php
use CRM_Reimbursement_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_ReimbursementCaseTypeConfig',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'ReimbursementCaseTypeConfig',
        'label' => E::ts('ReimbursementCaseTypeConfig'),
        'api_entity' => 'ReimbursementCaseTypeConfig',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'case_type_id:label',
            'expense_type_ids:label',
            'expense_status_id:label',
            'initial_case_status_id:label',
            'submit_case_status_id:label',
            'writable_case_status_ids:label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_ReimbursementCaseTypeConfig_SearchDisplay_ReimbursementCaseTypeConfig_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'ReimbursementCaseTypeConfig_Table',
        'label' => E::ts('ReimbursementCaseTypeConfig Table'),
        'saved_search_id.name' => 'ReimbursementCaseTypeConfig',
        'type' => 'table',
        'settings' => [
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'case_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Case Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'expense_type_ids:label',
              'dataType' => 'Integer',
              'label' => E::ts('Available Expense Types'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'expense_status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Expense Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'initial_case_status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Initial Case Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'submit_case_status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Submit Case Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'writable_case_status_ids:label',
              'dataType' => 'Integer',
              'label' => E::ts('Writable Case Status'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => 'ReimbursementCaseTypeConfig',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'ReimbursementCaseTypeConfig',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          'toolbar' => [
            [
              'entity' => 'ReimbursementCaseTypeConfig',
              'text' => E::ts('Add'),
              'icon' => 'fa-plus',
              'target' => 'crm-popup',
              'action' => 'add',
              'style' => 'primary',
              'join' => '',
              'path' => '',
              'task' => '',
              'conditions' => [],
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
